name: Create test tweak
on:
  push:
  pull_request:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish Enmity tweak and force local IP
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          submodules: true

      - name: Check cache
        id: verify-cache
        run: |
          echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1`"

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ steps.verify-cache.outputs.heads }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build dev deb
        run: |
          rm -f packages/*
          echo $"$(sed 's/Name\:.*/Name\: Enmity (Dev)/' control)" > control
          echo $"$(sed 's/Package\:.*/Package\: app.enmity.dev/' control)" > control
          gmake clean package FINALPACKAGE=1 DEVTOOLS=1
          mv $(find packages -name "*.deb" -print -quit) out/Enmity.Development.deb
          
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: test_tweak
          title: Testing Enmity Tweak
          files: out/*.deb
